export const cartShopData = [
    {
        name:'水果',
        id:1,
        children:[
            {
                name:'苹果',
                price:20.23,
                id:11,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic2.chinaz.net/Files/pic/pic9/201905/bpic11745_s.jpg'
            },
            {
                name:'挑子',
                price:20.23,
                id:12,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic3.chinaz.net/Files/pic/pic9/202108/apic34893_s.jpg'
            },
            {
                name:'橘子',
                price:20.23,
                id:13,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic2.chinaz.net/Files/pic/pic9/201306/xpic11854_s.jpg'
            },
            {
                name:'枣子',
                price:20.23,
                id:14,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic.chinaz.net/Files/pic/pic9/201305/xpic11374_s.jpg'
            }
        ]
    },
    {
        name:'应季蔬菜',
        id:2,
        children:[
            {
                name:'绿叶菠菜',
                price:20.23,
                id:21,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic2.chinaz.net/files/default/imgs/2022-10-08/e9ba670456a0be63_s.jpg'
            },
            {
                name:'西兰花',
                price:20.23,
                id:22,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic.chinaz.net/Files/pic/pic9/201808/bpic7799_s.jpg'
            },
            {
                name:'辣椒',
                price:20.23,
                id:23,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic.chinaz.net/Files/pic/pic9/201807/bpic7492_s.jpg'
            },

        ]
    },
    {
        name:'面食',
        id:3,
        children:[
            {
                name:'鸡蛋面',
                price:20.23,
                id:31,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic1.chinaz.net/Files/pic/pic9/201707/zzpic4831_s.jpg'
            },
            {
                name:'意大利面',
                price:20.23,
                id:32,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic.chinaz.net/files/default/imgs/2022-08-14/4fe4bd56f36e88c1_s.jpg'
            },
            {
                name:'饺子',
                price:20.23,
                id:33,
                goodNum:0,
                monthlySales:10,
                logo:'https://scpic1.chinaz.net/Files/pic/pic9/201801/zzpic9452_s.jpg'
            },

        ]
    }
]